# Generated by Django 3.2.7 on 2021-09-15 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_person_phone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
